### ISSUE TITLE
Namespace register nog niet gevuld

### ISSUE THREAD

**Issue by milovanderlinden** [codefornl/INSPIRE#1]
Het namespace register is nog niet gevuld. Dit maakt het registreren lastig en vereist dus afstemming met de betrokken autoriteiten.

**Comment by HerzovanderWal** [comment]
Als ik het goed begrijp dient er voor elk ruimtelijk object een INSPIRE-ID te zijn die opgebouwd is uit de namespace, de lokale ID en optioneel een versie indicatie. Iets als nl_sluis_nr1_v199212. Ik stel voor dat ik deze namespaces op neem als voorstel in Metadata_INSPIRE.xlsx

**Comment by milovanderlinden** [comment]
For Hydro we have agreed to use:
https://geodata.nationaalgeoregister.nl/inspire/hy-n/
If we add a version, it should be added as a separate subresource identifier, like so:
https://www.rws.nl/inspire/nl.hydro.network.rws/2017

**Comment by HerzovanderWal** [comment]
@milovanderlinden - Thank you for your hint. In the meeting with Geonovum today we decided not to ad the nl namespace untill there is a compleet harmonised data -service. In the official services from harmonized data we don't use the organisation-namespace. Example rws. In providing services, we do. For example WeTransform is making harmonized data for RWS and makes the data available for PDOK by services. In these URI is the organisation namespace rws. PDOK will host the services without the organisation namespace. The Namespaces are defined in Metadata_INSPIRE.xlsx and soon declared in http://inspirelab.geonovum.nl/namespaces/listnamespaces.php, the NL INSPIRE Namespace Register. From there we work on we buils up the INSPIRE-ID's. Agreed??

**Comment by milovanderlinden** [comment]
That is good. So the task has now been transformed to Geonovum to update their registry.
