### ISSUE TITLE
Add Network, Nodes and Links to TN-W

### ISSUE THREAD

**Issue by thorsten-reitz** [codefornl/INSPIRE#16]
- Interpret all vaarwegvakken as `InlandWaterways`, as there is no attribute to distinguish them
- Interpret all kmmarkeringen as `WaterwayNodes`

**Comment by HerzovanderWal** [comment]
Thats what we agreed. What is a tn-w label?

**Comment by HerzovanderWal** [comment]
Aha - this the creation of milestones you mentioned.

**Comment by HerzovanderWal** [comment]
Thorsten, please - look in xlsx for namespaces RWS declared. 
hy-n -> hydrograhy network
tn-ro -> DTB- or NWB-W- (depends on mapping)
tn-wtn -> waterway transport network

**Comment by thorsten-reitz** [comment]
There is no meaningful way to generate the nodes form this data set, so they will be omitted.

**Comment by alfredpellemans** [comment]
@Thorsten. You are right about the meaning of wvk_id. If an id of a kmmarkering is not available or refers to a non existing vaarwegvak, the kmmetrering may be skipped. This has to be repaired in the source data.
![afbeelding](https://user-images.githubusercontent.com/34025968/33263784-5d772d9e-d36b-11e7-97d2-1674120db8d4.png)

**Comment by alfredpellemans** [comment]
A good source for the nodes between vaarwegvak is the dataset that is published from http://vaarweginformatie.nl. The RIS index provide all required nodes. In de page downloads (>vaagweginformatie>downloads, you can find the RIS index. This is the table (excel). The function "JUNCTION" represents the links between vaarwegvakken (here called SECTION). In this table also all kmmarkeringen are included (DISMAR, distance marks).

**Comment by HerzovanderWal** [comment]
Well. thank you. @alfredpellemans - @thorsten-reitz  this dataset is part of the formal dataset ViN. That RWS can use. Is this helpfull for you?

**Comment by thorsten-reitz** [comment]
@alfredpellemans @HerzovanderWal yes, this is helpful. It will require making a change to the mapping. Basically I need to make a Groovy Join, and only emit `MarkerPost` objects if the join was successful.

With respect to the excel table, I can use that too. I was just wondering whether I should make a separate alignment to work with this, since it depends on an Excel file resource, so automation couldn't happen like it could with WFS sources.

**Comment by alfredpellemans** [comment]
I found the WFS webservice of the RIS Index (and more)
https://www.vaarweginformatie.nl/wfswms/services?SERVICE=WFS&VERSION=1.3.0&REQUEST=GetCapabilities

feature=ISRS serves the RIS Index.

By the way, via this service you will also find  :
Section
SectionJuntion
KilometerMark
Navigability (= CEMT class)

Fairway (=number of connected Sections)
Route (=number of connected Fairway)

The whole list of features from this webservice :
Administration
AimedLevel
AimedWaterlevel
AnchorageArea
AnchorageBerth
Berth
Bridge
BunkerStation
Buoy
CarDropoff
Chamber
Checkpoint
ClassificationData
ClusterElement
Corridor
Dam
ExceptionalNavigationalStructure
Fairway
FairwayClassification
FairwayConnection
FairwayDepth
FairwayStatus
FairwayType
Ferry
FerryLandingPoint
FishingHarbour
Ftm
FtmSource
GeoGeneration
GeoObject
GoodsTransShipment
HeadOffice
Hulk
IceTrajectory
Icem
Identification
Instance
Isrs
IsrsData
KilometerMark
Lock
MGDTrajectory
MaximumDimensions
MaximumSpeed
Municipality
Navigability
NwbHarbour
OfficialLevel
Opening
OperatingPeriod
OperatingRule
OperatingTimes
OverheadCable
OverheadPipe
Particularity
PilotRegion
PleasureCraftWaterwayClassification
Plov
Pontoon
PortArea
PushTowAnchorage
RadioCallInPoint
RefuseDump
Regulation
RelatedObject
Route
RouteJunction
SABCollectionPoint
Section
SectionId
SectionJunction
ServiceHarbour
ShorelineConstruction
SpecialProvision
SubInstance
Subchamber
TouristHarbour
TrafficSignalStation
TrailerSlipway
TrajectoryAdministration
TrajectoryTrait
TurningBasin
VinHarbour
VtsSector
VtsSubsector
WaitingArea
WaterLevelNAP
WaterwayGauge
Werm
WorkingArea
Wrm
