### ISSUE TITLE
Create hy-n alignment

### ISSUE THREAD

**Issue by thorsten-reitz** [codefornl/INSPIRE#18]
Deliver an alignment that transforms `dmlinks` and `dmnodes` to the INSPIRE Hydrography Network theme.

**Comment by HerzovanderWal** [comment]
Question @HerzovanderWal - Should this namespace fragment be used as the dataset identifer in the namespace, e.g. like so?

https://www.rijkswaterstaat.nl/hy-n/

Or should it be used as part of the feature IDs?

hy-n.{FEATURETYPENAME}.{SOURCE_ID}

Or both :)? Answer to @thorsten-reitz - Not both!
Yes like: https://www.rijkswaterstaat.nl/hy/hy-n/      And then feature IDs like 
{FEATURETYPENAME}.{source}-{SOURCE_ID}
sample?: watercourseseparatedcrossing.dtb-{SOURCE_ID}
full URL:
https://www.rijkswaterstaat.nl/hy/hy-n/watercourseseparatedcrossing.dtb-{SOURCE_ID}

Will this work? Suggestions?
