### ISSUE TITLE
Automate processing and publishing of TN-RO dataset

### ISSUE THREAD

**Issue by thorsten-reitz** [codefornl/INSPIRE#25]
In the scope of this task, the hale connect configuration for TN-RO (theme and dataset) as well as the hale studio transformation project is updated to ensure fully automated updates every month. This task includes:

- [x] Use WFS data sources in the transformation project where possible
- [ ] Publish source data sets that are not available through WFS as haleconnect WFS
- [x] Update theme configuration to automatically update everything every month

**Comment by JohannaOtt** [comment]
schemas
created from files downloaded via DescribeFeatureType request - have to be refreshed once schemas created from WFS can be used with data:
NWB: https://haleconnect.com/#/schema/org/292/b262efc6-a9c0-4d03-a0af-1d2dededffb1/overview
Weggeg: https://haleconnect.com/#/schema/org/292/0fef2caf-166c-47af-b750-36166ccc1b1b/overview
DTB: https://haleconnect.com/#/schema/org/292/be23420e-d040-409e-8d34-b0ae2a4d2959/overview
created from hsd exported using the FGDB in hale studio - has to be refreshed once RoadJunctions are delivered via WFS:
RoadJunctions: creating schema from hsd fails

**Comment by JohannaOtt** [comment]
theme
using relevant feature types from the schemas mentioned above:
https://haleconnect.com/#/theme/INSPIRENLTN-RO-1536130281345/overview

missing: feature types from RoadJunctions as schema creation did not work yet

**Comment by JohannaOtt** [comment]
dataset
using downloaded vlakken.zip (dataset too big to directly download it from WFS)
using wegvakken and hectopunten from WFS
using downloaded weggeg.gml (does not validate because of ids not being unique, certificate has been changed - will only load from WFS after next deploy)
https://haleconnect.com/#/dataset/org/292/fedc2fa4-36ad-4aab-a324-07038cdf7bdf/overview

missing: feature types from RoadJunctions as schema creation did not work

**Comment by JohannaOtt** [comment]
transformation project
https://haleconnect.com/#/transformation/org/292/39814b4b-c7e5-4811-b48c-40d09cd1278d/overview

target theme
https://haleconnect.com/#/theme/INSPIRENLRoad-1542099657045/overview

**Comment by JohannaOtt** [comment]
transformed data
https://haleconnect.com/#/dataset/org/292/b77be65b-e16f-4e59-b437-e13bff1dce98/overview

**Comment by JohannaOtt** [comment]
The namespace of the NWBwegen-WFS changed once more (see https://geodata.nationaalgeoregister.nl/nwbwegen/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=DescribeFeatureType).
This causes a need for changes at several places (combined schema, importing data from WFS) of the alignment as well as in the online configuration (schema, data).

**Comment by HerzovanderWal** [comment]
I'm sorry that you are not informed about this change. I passed this message to the provider. In order to get a message when a change like this takes place.

**Comment by JohannaOtt** [comment]
The namespace changed from "http://example.org/pdok/nwbwegen" to "http://nwbwegen.geonovum.nl".
This change has only be applied to for the DescribeFeatureType-Request (https://geodata.nationaalgeoregister.nl/nwbwegen/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=DescribeFeatureType). It contains "targetNamespace="http://nwbwegen.geonovum.nl" ".
The GetCapabilities-Request (https://geodata.nationaalgeoregister.nl/nwbwegen/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=getcapabilities) still contains the namespace "xmlns:nwbwegen="http://example.org/pdok/nwbwegen"" as attribute in the root element for the definition of the feature types' namespace. Those two namespaces should be aligned.
