### ISSUE TITLE
Automate processing and publishing of HY-N dataset

### ISSUE THREAD

**Issue by thorsten-reitz** [codefornl/INSPIRE#26]
In the scope of this task, the configuration for the HY-N dataset and theme are updated to ensure fully automated publishing and updating every month. This task includes:

- [x] Use WFS data sources in the transformation project where possible
- [x] Publish source data sets that are not available through WFS as haleconnect WFS
- [x] Update theme configuration to automatically update everything every month

**Comment by JohannaOtt** [comment]
schema
created from files downloaded via DescribeFeatureType request - have to be refreshed once schemas created from WFS can be used with data:
NHI: https://haleconnect.com/#/schema/org/292/86a07c55-7d2d-4248-9dbf-6c4c00b49fde/overview

**Comment by JohannaOtt** [comment]
theme
using all relevant feature types from the schema mentioned above:
https://haleconnect.com/#/theme/INSPIRENLHY-N-1542034244184/overview

**Comment by JohannaOtt** [comment]
dataset
using downloaded dmlinks (WFS download after deploy)
using downloaded dmnodes (WFS download after deply)
https://haleconnect.com/#/dataset/org/292/23f5f9c0-0682-470e-b5e3-f33be8d69a4c/overview

transformation project
https://haleconnect.com/#/transformation/org/292/9a99e6c6-03a5-48cf-876f-e5d33d08d600/overview

target theme
https://haleconnect.com/#/theme/INSPIRENLHydro-1542099815520/overview

**Comment by JohannaOtt** [comment]
transformed data
https://haleconnect.com/#/dataset/org/292/c3955762-73a3-4c16-a15c-f3869487a1e3/overview

WMS
https://haleconnect.com/ows/services/org.292.c3955762-73a3-4c16-a15c-f3869487a1e3_wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0

WFS
https://haleconnect.com/ows/services/org.292.c3955762-73a3-4c16-a15c-f3869487a1e3_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0
