### ISSUE TITLE
Automate processing and publishing of TN-W dataset

### ISSUE THREAD

**Issue by thorsten-reitz** [codefornl/INSPIRE#27]
In the scope of this task, the hale connect configuration (dataset and theme) and the hale studio transformation project for the TN-W are updated to ensure fully automated publishing and updating every month. This task includes:

- [x] Use WFS data sources in the transformation project where possible
- [x] Publish source data sets that are not available through WFS as haleconnect WFS
- [x] Update theme configuration to automatically update everything every month

**Comment by JohannaOtt** [comment]
schemas
created from files downloaded via DescribeFeatureType request - have to be refreshed once schemas created from WFS can be used with data:
NWB Vaarwegen Kmarkeringen: https://haleconnect.com/#/schema/org/292/c0cf6f84-6286-4c33-a986-5bb67e4e33a1/overview
Markdrijvendrd Markvastrd: https://haleconnect.com/#/schema/org/292/e4dc9274-cbc8-450d-a52e-d9da84a71b7e/overview
Verkeerscheidingstelsel: https://haleconnect.com/#/schema/org/292/1a2cba9f-6d7e-430d-99e5-ac6dd580833a/overview

**Comment by JohannaOtt** [comment]
theme
using all relevant feature types from the schemas mentioned above:
https://haleconnect.com/#/theme/INSPIRENLTN-W-1536058531795/overview

**Comment by JohannaOtt** [comment]
dataset
using downloaded Markvastrd Markdrijvendrd.zip from older datasets on hc (WFS download does not work right now)
using downloaded Vaarwegvakken Kmmarkeringen.zip from older datasets on hc (WFS download does not work right now)
using downloaded separatieZones.gml from older datasets on hc (WFS download does not work right now)
https://haleconnect.com/#/dataset/org/292/3e7ee520-7a4f-404f-b5ea-120e37bb4eba/overview

**Comment by JohannaOtt** [comment]
transformation project
https://haleconnect.com/#/transformation/org/292/f33f18d0-4c83-4e66-a80f-43b3fb885a1f/overview

target theme
https://haleconnect.com/#/theme/INSPIRENLWater-1536313503666/overview

**Comment by JohannaOtt** [comment]
transformed data
https://haleconnect.com/#/dataset/org/292/2885ef73-e044-4da4-b9b6-8a461a5353aa/overview
