### ISSUE TITLE
Create alignment for Noise data

### ISSUE THREAD

**Issue by thorsten-reitz** [codefornl/INSPIRE#28]
Based on the resources made available by RWS through WFS and other sources, we will develop a hale studio 3.4.0+ transformation project, to generate INSPIRE Human Health and Safety data from the following source data sets:

-	Geluidbelasting rijkswegen in Nederland 2016 (nacht gemiddelde)
-	Geluidbelasting rijkswegen in Nederland 2016 (24-uurs gemiddelde)
-	Geluidbelasting rijkswegen in Nederland 2011 (nacht gemiddelde)
-	Geluidbelasting rijkswegen in Nederland 2011 (24-uurs gemiddelde)
-	Geluidbelasting rijkswegen in Nederland 2006 (nacht gemiddelde)
-	Geluidbelasting rijkswegen in Nederland 2006 (24-uurs gemiddelde)

**Comment by HerzovanderWal** [comment]
When will it be available?

**Comment by JohannaOtt** [comment]
I created a first version of the alignment. Questions/open points that appeared:

    there seems to a discrepancy between the Measure-Type that should be used according to the INSPIRE Data Specification (https://inspire.ec.europa.eu/id/document/tg/hh) and the one used in the INSPIRE xsd (https://inspire.ec.europa.eu/schemas/hh/4.0/HumanHealth.xsd). The Data Specification demands the ISO 19105 Measure-Type while the xsd is using the gml:Measure-Type. This is also mentioned (although not really discussed/explained) in a Thematic Cluster discussion and I asked Kathi Schleidt for clarification: https://themes.jrc.ec.europa.eu/discussion/view/53288/environmental-noise-directive
    For now, this means that the EIONET codelist the Data Specification demands to use in chapter 5.3.1.2.3. cannot be used. This will have to be changed once the INSPIRE xsd is updated. I will add a comment once I got a reply from Kathi Schleidt on the current state of this issue.

    I can't find any information on the unit of measure used for the Geluidsbelasting data. I assume the values are in dB(A). @HerzovanderWal who can I ask for confirmation?

    The data model does not provide for the use of ranges for the measures. I decided to take the lower value from the source object ("class_min" for the 2006 & 2011 data and "ondergrens" for the 2016 data). @HerzovanderWal if you prefer taking the higher value or a an average value instead, I can change the alignment accordingly.

**Comment by JohannaOtt** [comment]
replies from Renez Nota (via mail):

- Correct, values are in dB(A)

- Yes, “ondergrens” in the 2016 data is the equivalent of “class_min” in the 2006 and 2011 data. By definition, noise contour surfaces represent a range of noise levels, between “class_min” and “class_max” in 2006 & 2011 and between “ondergrens” and “bovengrens” in 2016. All of these datasets also contain a text field with a description of the noise level range, like “54.5 - 59.5” for example.
If you are looking for the discrete noise level boundaries (at the intervals specified by the END), we also have isophone lines available from the 2016 noise mapping. If you are interested, I could check our archives for similar data for 2006 and 2011, but I can’t make any promises about their availability since they are not END-deliverables.

**Comment by JohannaOtt** [comment]
update from emails (extracts):

Johanna 23.11. :"As INSPIRE does not provide for the use of ranges, discrete noise level boundaries would make more sense in my oppinion. Are the 2016 isophone lines you are mentioning available publicly somewhere? If the older lines data is not published right now it does not have to be transformed to the INSPIRE model,"

Renez 27.11.: "The 2016 isophone lines are not publicly available. Is that a requirement? If not, I could just transfer them to you."

Johanna 28.11.: "Thank you for the information. As the isophone lines are not publicly available, they are not the right source data for the INSPIRE data we are going to provide.

We will go on using the polygon features that are available - thank you for your help!"

**Comment by JohannaOtt** [comment]
availability on haleconnect:

- source schema created from file downloaded via DescribeFeatureType request - has to be refreshed once schemas created from WFS can be used with data (ING-1161): https://haleconnect.com/#/schema/org/292/2f09cf73-8025-447e-876d-54c012592d55/overview

- source theme: https://haleconnect.com/#/theme/NLGeluidskaarte-1544170515917/overview

- target schema: https://haleconnect.com/#/schema/org/292/d20b09c7-89b5-4aa1-b147-84a649ed1516/overview

- target theme: https://haleconnect.com/#/theme/INSPIREHumanHe-1544170619599/overview

- transformation project: https://haleconnect.com/#/transformation/org/292/dce135e0-1db2-4994-932c-98c4405e4d1b/overview

- source data: https://haleconnect.com/#/dataset/org/292/9afd77e2-9625-4a80-a6d2-4babd9b9d1f9/overview

- transformed data: https://haleconnect.com/#/dataset/org/292/ad829021-562e-40ab-89ab-863b4771d387/overview

**Comment by HerzovanderWal** [comment]
Thanks:
I find: INSPIRE Human Health
I expect: INSPIRE NL Human Health and Safety Noise

We want to keep the terms as close as possible to the INSPIRE guidelines (language)

**Comment by JohannaOtt** [comment]
I changed it accordingly.

**Comment by JohannaOtt** [comment]
update: Kathi replied on the schema issues: https://themes.jrc.ec.europa.eu/discussion/view/53288/environmental-noise-directive
I will only be able to have a look at her input in January.

**Comment by JohannaOtt** [comment]
Update: Kathi Schleidt pointed out in the Thematic Cluster thread that the use of the gml:Measure-Type is valid. Still, the EIONET codelist the Data Specification demands to use in chapter 5.3.1.2.3. cannot be used with it. We will contact the JRC on that question and add comments to this thread once they clarified how the EIONET codelist values can be used (or if they are willing to adapt the XSD accordingly).

**Comment by JohannaOtt** [comment]
Update: There has been an IR change proposal concerning the INSPIRE Human Health and Safety theme: https://inspire.ec.europa.eu/forum/discussion/view/261192/envhealthdeterminantmeasure-how-to-express-the-type-of-noise-measure#elgg-object-261325. Once it is decided if it gets accepted, we are hopefully able to use the EIONET codelist as intended.
Note: the URL to the EIONET codelist changed (new value can be taken from the thread linked above).
