### ISSUE TITLE
Transform Geometry

### ISSUE THREAD

**Issue by milovanderlinden** [codefornl/INSPIRE#3]
Omdat de rijkswaterstaat WFS services DEFAULT in RD (EPSG:28992) uitleveren moet transformatie van de geometrie plaatsvinden voor alle geometrie.

**Comment by thorsten-reitz** [comment]
What CRS should the final delivery use? The INSPIRE CRS include:

* Web Mercator (EPSG:3857)
* WGS84 (EPSG:4326)
* LAEA (EPSG:3035)

**Comment by HerzovanderWal** [comment]
Is ETRS an availabel CRS?

**Comment by milovanderlinden** [comment]
That is the only one in the list that is not understood by OpenLayers, Leaflet, Esri Javascript and Google Maps out of the box. This will add an extra hurdle for non-geo developers to adapt. 

I would strongly advice to use WGS84. The users of the INSPIRE services will thank you for that in advance.

**Comment by thorsten-reitz** [comment]
I can also provide both.

**Comment by HerzovanderWal** [comment]
THat would be the answer: We provide both.
