### ISSUE TITLE
Kaderrichtlijnwater service returns incorrect URL

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [codefornl/INSPIRE#31]
If you look at what the server returns for the `GetCapabilities` request you can see that it returns the URL like this, with a colon:
```
<ows:Operation name="DescribeFeatureType">
  <ows:DCP>
    <ows:HTTP>
      <ows:Get xlink:type="simple" xlink:href="http://geodata.nationaalgeoregister.nl:/kaderrichtlijnwater/wfs?language=dut&"/>
      <ows:Post xlink:type="simple" xlink:href="http://geodata.nationaalgeoregister.nl:/kaderrichtlijnwater/wfs?language=dut&"/>
    </ows:HTTP>
  </ows:DCP>
...
</ows:Operation>
```

The service returns invalid URLs. There should not be a colon after `http://geodata.nationaalgeoregister.nl:`.

**Comment by HerzovanderWal** [comment]
The error in the service is mentioned to service provider PDOK. On hold.

**Comment by Kate-Lyndegaard** [comment]
I tested the updated service and it looks like the error has been fixed 👍
