### ISSUE TITLE
deliver RoadJunction data as WFS

### ISSUE THREAD

**Issue by JohannaOtt** [codefornl/INSPIRE#38]
The RoadJunction data is currently delivered as FGDB. It is supposed to be delivered via WFS in the future.

**Comment by HerzovanderWal** [comment]
Bring up the service with Hale-connect and use that service foor the time being.

**Comment by JohannaOtt** [comment]
I will do - but if I remember right, Peter said that it will be available as WFS one day, so I wanted to document that it need to be changed once it is available.

**Comment by HerzovanderWal** [comment]
The estimated moment that the PDOK-service will be public is the second half of 2019!
