### ISSUE TITLE
Stored query

### ISSUE THREAD

**Issue by HerzovanderWal** [codefornl/INSPIRE#39]
What are the issues that come with stored query? Are the delivered services and there metadata compliant at this subject?

**Comment by thorsten-reitz** [comment]
We are aware of a validation issue with respect to a missing operation:

`the WFS is missing information on ISO 19143 'Minimum Temporal Filter' (TG Requirement 67)
for more infos, please check related WGS ticket`

Are you referring to this particular issue?

**Comment by HerzovanderWal** [comment]
I'm not shore. When I deliver the HALE-connect WFS-service to the EU-INSPIRE-portal would the data off all off the feuturetypes be available for download? Or only the first one?
