### ISSUE TITLE
noordzeevaarwegmarkeringenrd WFS does not return markdrijvendrd features any more

### ISSUE THREAD

**Issue by JohannaOtt** [codefornl/INSPIRE#40]
The request used so far does not retuen any features any more: https://geodata.nationaalgeoregister.nl/noordzeevaarwegmarkeringenrd/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&NAMESPACES=xmlns(noordzeevaarwegmarkeringenrd,http://noordzeevaarwegmarkeringenrd.geonovum.nl)&TYPENAMES=noordzeevaarwegmarkeringenrd:markdrijvendrd

@HerzovanderWal is there someone from PDOK in this repository I could assign that issue to?

**Comment by HerzovanderWal** [comment]
For me there is a strange https:// and HTTP:// mixture in the url. Ask the provider PDOK what they have changed.

**Comment by JohannaOtt** [comment]
Is one of them active in this repository or do you have an email address of a person in charge? Their contact sheet is not available in English unfortunately: https://formulieren.kadaster.nl/contact-pdok

**Comment by thorsten-reitz** [comment]
@JohannaOtt you can contact PDOK directly as a user of the service.

**Comment by JohannaOtt** [comment]
The service seems to work again - 9294 mardrijvendrd objects are returned. I will add them to the relevant Dataset on haleconnect today.
