### ISSUE TITLE
Link local provider PDOK with HALE-connect services

### ISSUE THREAD

**Issue by HerzovanderWal** [codefornl/INSPIRE#45]
We would like to update our INSPIRE-services. Are the aligned data-services available? Where can we find them?

**Comment by HerzovanderWal** [comment]
> We would like to update our INSPIRE-services. Are the aligned data-services available? Where can we find them?

@thorsten-reitz

**Comment by thorsten-reitz** [comment]
Hi Herzo, the URLs are included in the respective tickets:

Noise:
https://github.com/codefornl/INSPIRE/issues/28

TN-RO:
https://github.com/codefornl/INSPIRE/issues/25

TN-W:
https://github.com/codefornl/INSPIRE/issues/27

HY-N:
https://github.com/codefornl/INSPIRE/issues/26

Elevation will be available next week - Johanna was out for a few days.
