### ISSUE TITLE
AHN - Elevation transformatie inrichten

### ISSUE THREAD

**Issue by milovanderlinden** [codefornl/INSPIRE#5]
Het AHN dient gemapped te worden op het elevation thema https://inspire.ec.europa.eu/Themes/118/2892

**Comment by milovanderlinden** [comment]
De ahn metadata is verkrijgbaar via de WFS op http://geoservices.rijkswaterstaat.nl/ahn_nl_metadata?service=wfs&request=getcapabilities

**Comment by milovanderlinden** [comment]
De mapping is niet duidelijk. Deze dient als vraag bij de bronhouder te worden neergelegd.

**Bronnen**
- AAA400 puntdichtheid 1996-2003
- AAA500 stadspolygonen 1996-2003
- AAA600 vliegdatum per strook 1996-2003

**Doelen**
- Base types http://inspire.ec.europa.eu/schemas/el-bas/4.0/ElevationBaseTypes.xsd
- Grid Coverage http://inspire.ec.europa.eu/schemas/el-cov/4.0/ElevationGridCoverage.xsd
- TIN http://inspire.ec.europa.eu/schemas/el-tin/4.0/ElevationTin.xsd
- Elevation http://inspire.ec.europa.eu/schemas/el-vec/4.0/ElevationVectorElements.xsd

**Comment by HerzovanderWal** [comment]
De mapping wordt in de komende maanden gestart!
