### ISSUE TITLE
AHN alignment coördinates

### ISSUE THREAD

**Issue by HerzovanderWal** [codefornl/INSPIRE#55]
Is there a difference in the coördinates that describe the AHN1  data and provided by the AHN1 services? The data seems to be delivered in EPSG 28992 hor. and EPSG 5730 vert.. What are the coördinate systems expected by INSPIRE?

**Comment by JohannaOtt** [comment]
Hi Herzo,
I am not entirely sure if I understand your question correct. Is it about the source data or the transformed data?
INSPIRE allows different coordinate systems:
![grafik](https://user-images.githubusercontent.com/34163838/69317986-75ac0400-0c3c-11ea-8fa1-bf1344379e41.png)
The datasets I uploaded are exported in EPSG:4258.

**Comment by HerzovanderWal** [comment]
Thanks, the recommendation in the Netherlands is ETRS89+EVRS as 3D CRS for height of land, inland waterbottom and coastal waterbottom shallower as 10 mtr LAT. That is the focus
