### ISSUE TITLE
Geluidszonering - Noise exposure

### ISSUE THREAD

**Issue by milovanderlinden** [codefornl/INSPIRE#6]
Volgens de specificatie in https://inspire.ec.europa.eu/file/1537/download?token=Uk33dqjm dienen geluidszoneringen ook te worden getransformeerd in het kader van het thema Human Health and Safety

https://inspire.ec.europa.eu/Themes/119/2892

**Comment by milovanderlinden** [comment]
http://geoservices.rijkswaterstaat.nl/dvs_geluidskaarten?service=wfs&request=getcapabilities

**Comment by milovanderlinden** [comment]
https://circabc.europa.eu/webdav/CircaBC/env/noisedir/Library/Noise%20Expert%20Group/Meetings/2017_02_28/2016_INSPIRE_Reporting_of_Strategic_Noise_Maps(0).pdf

**Comment by milovanderlinden** [comment]
lne vlaanderen heeft deze transformatie mogelijk al uitgevoerd. Contact opnemen?

**Comment by milovanderlinden** [comment]
Het is niet helemaal duidelijk of Human Health and Safety het juiste thema is. Eerst uitzoeken.

**Comment by HerzovanderWal** [comment]
Menselijke gezondheid en veiligheid (Human Health and Safety ) is het voorlopig geworden.
