### ISSUE TITLE
Feature definitions in structere data or in content data

### ISSUE THREAD

**Issue by HerzovanderWal** [codefornl/INSPIRE#7]
The tree of INSPIRE definitions is complex for creating data-services. So the question is how we generalise the data and how do we we add the required definitions in the data and or metadata?

**Comment by milovanderlinden** [comment]
Geoserver should be able to serve complex features. I have done this in the past for the IMDBK from Geonovum. @NielsCharlier is the guy that might be able to help you out __if__ Geoserver is the server that will be used.

**Comment by NielsCharlier** [comment]
That is correct, there is a supported extension called application schema which serves complex features based on a mapping.

**Comment by milovanderlinden** [comment]
@HerzovanderWal can you please let me know if this is an answer to your question and if you know how to continu from here? Then I can close this issue.

Thank you in advance!

**Comment by HerzovanderWal** [comment]
@milovanderlinden it is the technical part in the answer to my question. The part is about the implementing of the possibility's. I got that from Geonovum to day. I can make choices now. Thank you.
